### ISSUE TITLE
集成都项目中运行会报错

### ISSUE THREAD

**Issue by FrankChung1121** [nothot/DUAReader#10]
-[__NSCFString rangeOfParagraphsContainingRange:parBegIndex:parEndIndex:]: unrecognized selector sent to instance

在modal出来小说读取器后，总会出现上面的崩溃信息

**Comment by nothot** [comment]
你仔细对比demo工程和你工程的buildseting配置，尤其是linker flag选项，framework search path，这个很显然是DTCoretext没找到

**Comment by FrankChung1121** [comment]
好的，谢谢大佬
