### ISSUE TITLE
swift 3 能用这个吗？？

### ISSUE THREAD

**Issue by 294230507** [nothot/DUAReader#4]

**Comment by nothot** [comment]
这个是基于swift4写的，swift3下运行可能需要少许改动的地方

**Comment by 294230507** [comment]
TouchXML 这个第三方库在哪里能下到 用pod 的话 应该是怎么用的?可以的话 能给个QQ什么的 先谢谢了

**Comment by nothot** [comment]
TouchXML在GitHub的地址: https://github.com/TouchCode/TouchXML ，framework是我通过源代码编译的。项目中用到的三个framework均在GitHub上有源码。
