### ISSUE TITLE
只能读本地的epub吗

### ISSUE THREAD

**Issue by zerorrr** [nothot/DUAReader#7]
还想再请问一下 这个只能读本地的epub吗？ 用url路径可以吗？

**Comment by nothot** [comment]
无所谓的，都可以。对阅读器而言，不参与网络下载等业务逻辑，在线的书籍你可以直接下载了阅读，也可以分章节下载了分章阅读，这些都是具体的业务需求

**Comment by zerorrr** [comment]
可是我把书换成别的就crash了啊。。 只能用你那两个。 epub和txt都不行

**Comment by nothot** [comment]
不会的，我是做过测试的。具体你可以分析下你的原因（提示，txt要有规范章节标题，解析是使用正则匹配识别章节的，具体可以看解析相关代码）
